service: vue-ssr-serverless

provider:
  name: aws
  runtime: nodejs8.10

functions:
  index:
    handler: handler.index
    events:
      - http:
          method: GET
          path: /{proxy+}

plugins:
  - serverless-offline
  