// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0aaffeb1-4f6d-4ff8-939e-9461ffd86439",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ct9xubD7S",
    "aws_user_pools_web_client_id": "4o28h4bcbnk071idmpcflufjvd"
};


export default awsmobile;
