// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9ef0473c-c077-4ef2-bd7c-4b5585ef7d4a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KiO5PaPE4",
    "aws_user_pools_web_client_id": "23qn2418u8njs80n99cs52a9qs"
};


export default awsmobile;
